x

diff --git a/.github/workflows/backend.yml b/.github/workflows/backend.yml
--- a/.github/workflows/backend.yml
+++ b/.github/workflows/backend.yml
@@ -68,52 +68,19 @@ jobs:
           SONAR_TOKEN: ${{ secrets.LOCAL_SONAR_TOKEN }}
           SONAR_HOST_URL: ${{ secrets.LOCAL_SONAR_HOST_URL }}
         run: |
-          # Set environment variables for debugging
-          Write-Host "SONAR_TOKEN: $env:SONAR_TOKEN"
-          Write-Host "SONAR_HOST_URL: $env:SONAR_HOST_URL"
+          PROJECT_KEY="com.salapp.career.launch:${{ matrix.service }}"
+          # No branch specified, assumes default branch
+          STATUS=$(curl -u "${SONAR_TOKEN}:" -s \
+            "${SONAR_HOST_URL}/api/qualitygates/project_status?projectKey=${PROJECT_KEY}" | \
+            jq -r '.projectStatus.status')
           
-          # Initialize the status variable
-          $quality_gate_status = "PENDING"
-          $maxRetries = 30
-          $retryCount = 0
+          echo "Quality Gate Status: $STATUS"
           
-          $Headers = @{
-            Authorization = "Bearer $env:SONAR_TOKEN"
-          }
-          
-          Write-Host "Header is: $Headers"
-          Write-Host "TOKEN = ${env:SONAR_TOKEN}"
-          
-          # Poll for the quality gate status
-          while ($quality_gate_status -eq "PENDING" -and $retryCount -lt $maxRetries) {
-            # Query the SonarQube API to get the quality gate status
-            $url = "$env:SONAR_HOST_URL/api/qualitygates/project_status?projectKey=bank-showcase"
-            Write-Host "HOST URL = $url"
-          
-            try {
-                # Get the raw response using Invoke-RestMethod
-                $response = Invoke-RestMethod -Uri $url -Headers $Headers -ErrorAction Stop
-          
-                Write-Host "Raw API Response: $response"
-          
-                # Retrieve quality gate status
-                $quality_gate_status = $response.projectStatus.status
-                Write-Host "Quality Gate Status: $quality_gate_status"
-          
-            } catch {
-                Write-Host "Error encountered: $_"
-                exit 1
-            }
-          
-            # Wait before the next retry
-            Start-Sleep -Seconds 10
-            $retryCount++
-          }
-          
-          if ($quality_gate_status -ne "OK") {
-              Write-Host "Quality Gate failed or timeout reached"
-              exit 1  # Fail the job if the quality gate is not OK
-          }
+          if [ "$STATUS" != "OK" ]; then
+            echo "Quality Gate failed for ${PROJECT_KEY}"
+            exit 1
+          fi
+
   sonar-main:
     runs-on: [ self-hosted, local, java21, maven ]
     if: github.ref == 'refs/heads/main' || github.event_name == 'workflow_dispatch'
